import React from 'react'

const page = () => {
  return (
    <div>

<p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Laboriosam repellendus autem repudiandae nesciunt ipsum voluptate enim quae ducimus sint, officia quidem aspernatur, nam, atque blanditiis quis modi magni ipsam distinctio?Lorem ipsum dolor sit amet consectetur adipisicing elit. Est laudantium optio iste doloremque neque commodi, quia voluptates distinctio eius delectus odio praesentium voluptatibus omnis laborum, necessitatibus nulla sapiente labore. Id. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Cum obcaecati totam rerum, qui facilis vero odio adipisci culpa recusandae ad, illum consequuntur ipsum consectetur nulla voluptatem repellat distinctio harum. Aut. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Laborum blanditiis necessitatibus quos placeat distinctio excepturi veniam nemo asperiores maxime expedita. Autem, nesciunt? Repellat, recusandae quas accusantium repudiandae sint illo vel. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia numquam eligendi illo assumenda. Rem nisi autem voluptatibus. Error temporibus, saepe voluptate, rem sint vitae consectetur quisquam alias quas dolores iure! Lorem ipsum dolor, sit amet consectetur adipisicing elit. Blanditiis adipisci minus veniam molestiae labore quos pariatur quis obcaecati, et nihil? Suscipit ullam aliquam eius consequuntur fugit adipisci sed placeat obcaecati. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Vero nobis ratione repellendus consequuntur, ipsa soluta laboriosam quis quaerat officia fugit, nemo quos dicta excepturi deleniti ex voluptatibus ullam vel dolor? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Cumque repellat, ea minima, iure accusantium nobis eos aspernatur accusamus vitae soluta placeat autem optio, atque ipsa deleniti in quisquam dignissimos? Accusantium!</p>


<p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Laboriosam repellendus autem repudiandae nesciunt ipsum voluptate enim quae ducimus sint, officia quidem aspernatur, nam, atque blanditiis quis modi magni ipsam distinctio?Lorem ipsum dolor sit amet consectetur adipisicing elit. Est laudantium optio iste doloremque neque commodi, quia voluptates distinctio eius delectus odio praesentium voluptatibus omnis laborum, necessitatibus nulla sapiente labore. Id. Lorem ipsum dolor sit, amet consectetur adipisicing elit. Cum obcaecati totam rerum, qui facilis vero odio adipisci culpa recusandae ad, illum consequuntur ipsum consectetur nulla voluptatem repellat distinctio harum. Aut. Lorem ipsum, dolor sit amet consectetur adipisicing elit. Laborum blanditiis necessitatibus quos placeat distinctio excepturi veniam nemo asperiores maxime expedita. Autem, nesciunt? Repellat, recusandae quas accusantium repudiandae sint illo vel. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Officia numquam eligendi illo assumenda. Rem nisi autem voluptatibus. Error temporibus, saepe voluptate, rem sint vitae consectetur quisquam alias quas dolores iure! Lorem ipsum dolor, sit amet consectetur adipisicing elit. Blanditiis adipisci minus veniam molestiae labore quos pariatur quis obcaecati, et nihil? Suscipit ullam aliquam eius consequuntur fugit adipisci sed placeat obcaecati. Lorem, ipsum dolor sit amet consectetur adipisicing elit. Vero nobis ratione repellendus consequuntur, ipsa soluta laboriosam quis quaerat officia fugit, nemo quos dicta excepturi deleniti ex voluptatibus ullam vel dolor? Lorem ipsum dolor sit, amet consectetur adipisicing elit. Cumque repellat, ea minima, iure accusantium nobis eos aspernatur accusamus vitae soluta placeat autem optio, atque ipsa deleniti in quisquam dignissimos? Accusantium!</p>

    </div>
  )
}

export default page